/* DELETE 'BSPQ21-E2' database*/
DROP SCHEMA IF EXISTS BSPQ21E2;
/* DELETE USER 'spq' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'localhost';

/* CREATE 'BSPQ21-E2' DATABASE */
CREATE SCHEMA BSPQ21E2;

/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'localhost' IDENTIFIED BY 'spq';

/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON BSPQ21E2.* TO 'spq'@'localhost';

