/* DELETE 'BSPQ21-E2' database*/
DROP SCHEMA IF EXISTS BSPQ21E2;
/* DELETE USER 'spq' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'%';

/* CREATE 'BSPQ21-E2' DATABASE */
CREATE SCHEMA BSPQ21E2;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'%' IDENTIFIED BY 'spq';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON BSPQ21E2.* TO 'spq'@'%';

/* TEST THE DATABASE BY CREATING A TABLE AND INSERTING AN EMPLOYEE
USE BSPQ21E2;
CREATE TABLE employee_info (id integer(3), name VARCHAR(20), address VARCHAR(20), department VARCHAR(20));
INSERT INTO employee_info values (001, 'Iker', 'Bilbao', 'IT')


