/* DELETE 'BSPQ21-E2' database*/
DROP SCHEMA IF EXISTS BSPQ21E2;
/* DELETE USER 'sd' AT LOCAL SERVER*/
DROP USER IF EXISTS 'sd'@'%';

/* CREATE 'BSPQ21-E2' DATABASE */
CREATE SCHEMA BSPQ21E2;
/* CREATE THE USER 'sd' AT LOCAL SERVER WITH PASSWORD 'sd' */
CREATE USER IF NOT EXISTS 'sd'@'%' IDENTIFIED BY 'sd';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'sd' AT LOCAL SERVER*/
GRANT ALL ON BSPQ21E2.* TO 'sd'@'%';

/* TEST THE DATABASE BY CREATING A TABLE AND INSERTING AN EMPLOYEE
USE BSPQ21E2;
CREATE TABLE employee_info (id integer(3), name VARCHAR(20), address VARCHAR(20), department VARCHAR(20));
INSERT INTO employee_info values (001, 'Iker', 'Bilbao', 'IT')


